### ISSUE TITLE
Is this normal

### ISSUE THREAD

**Issue by erik903** [idinium96/tf2autobot#88] opened 2020-10-13 18:55 UTC
![image](https://user-images.githubusercontent.com/41398918/95903360-53f8c580-0d96-11eb-80c5-0426c0c4bb6b.png)

Is this normal cause my account isn't 15 days old yet and maybe it's that or do I need to redo cause I messed up?

**Comment by idinium96** [comment] 2020-10-13 22:45
duplicate of #26

**Closed** 2020-10-14 10:07 UTC
Labels: bug, duplicate
